// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: api.proto

package gocourse17

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Reviewer_GetHistory_FullMethodName = "/review.Reviewer/GetHistory"
	Reviewer_SendReview_FullMethodName = "/review.Reviewer/SendReview"
)

// ReviewerClient is the client API for Reviewer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReviewerClient interface {
	GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error)
	SendReview(ctx context.Context, in *SendReviewRequest, opts ...grpc.CallOption) (*SendReviewResponse, error)
}

type reviewerClient struct {
	cc grpc.ClientConnInterface
}

func NewReviewerClient(cc grpc.ClientConnInterface) ReviewerClient {
	return &reviewerClient{cc}
}

func (c *reviewerClient) GetHistory(ctx context.Context, in *GetHistoryRequest, opts ...grpc.CallOption) (*GetHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHistoryResponse)
	err := c.cc.Invoke(ctx, Reviewer_GetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewerClient) SendReview(ctx context.Context, in *SendReviewRequest, opts ...grpc.CallOption) (*SendReviewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendReviewResponse)
	err := c.cc.Invoke(ctx, Reviewer_SendReview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReviewerServer is the server API for Reviewer service.
// All implementations must embed UnimplementedReviewerServer
// for forward compatibility.
type ReviewerServer interface {
	GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error)
	SendReview(context.Context, *SendReviewRequest) (*SendReviewResponse, error)
	mustEmbedUnimplementedReviewerServer()
}

// UnimplementedReviewerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReviewerServer struct{}

func (UnimplementedReviewerServer) GetHistory(context.Context, *GetHistoryRequest) (*GetHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHistory not implemented")
}
func (UnimplementedReviewerServer) SendReview(context.Context, *SendReviewRequest) (*SendReviewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendReview not implemented")
}
func (UnimplementedReviewerServer) mustEmbedUnimplementedReviewerServer() {}
func (UnimplementedReviewerServer) testEmbeddedByValue()                  {}

// UnsafeReviewerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReviewerServer will
// result in compilation errors.
type UnsafeReviewerServer interface {
	mustEmbedUnimplementedReviewerServer()
}

func RegisterReviewerServer(s grpc.ServiceRegistrar, srv ReviewerServer) {
	// If the following call pancis, it indicates UnimplementedReviewerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Reviewer_ServiceDesc, srv)
}

func _Reviewer_GetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewerServer).GetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reviewer_GetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewerServer).GetHistory(ctx, req.(*GetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reviewer_SendReview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewerServer).SendReview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Reviewer_SendReview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewerServer).SendReview(ctx, req.(*SendReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Reviewer_ServiceDesc is the grpc.ServiceDesc for Reviewer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reviewer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "review.Reviewer",
	HandlerType: (*ReviewerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHistory",
			Handler:    _Reviewer_GetHistory_Handler,
		},
		{
			MethodName: "SendReview",
			Handler:    _Reviewer_SendReview_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
